@url = http://localhost:3000

###
GET {{url}}/feed/posts

###
POST {{url}}/feed/posts
Content-Type: application/json

{
    "title": "My Post",
    "content": "Bla bla"
}

###
POST {{url}}/graphql
Content-Type: application/json

{
    "query": "{hello { views }}"
}